
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.3
    container_name: weaviate-getSolar
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
      - --scheme
      - "http"
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 30
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: "${OPENAI_API_KEY}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  weaviate_data:
    
