import dspy

class ResponseGenerator(dspy.Signature):
    """
    Generates a clean response based on the user query and the provided context.
    """

    user_query: str = dspy.InputField(desc="The user's query or question.")
    context: str = dspy.InputField(desc="Contextual information to help generate a clean response.")
    response: str = dspy.OutputField(desc="The generated clean, concise and relevant response.")

class ReactSignature(dspy.Signature):
    """
    Signature for the ReAct agent that retrieves relevant information from FAQs and vector databases based on user query and history of chat.
    """
    user_query = dspy.InputField(desc="The user's query or question.")
    history : dspy.History = dspy.InputField(desc="The history of the chat, which can be used to provide context for the response.")
    response = dspy.OutputField(desc="The response generated by the ReAct agent based on the user's query and history of chat.")