import dspy 
from typing import Literal, Dict, Any 

class FormSignature(dspy.Signature):
    """
    To output proper information of a person sending an inquiry, generate a unique 7 digit ID for the person as well.
    """
    enquiry: str = dspy.InputField(
        desc = "The enquiry of the person"
    )
    user_id: int = dspy.OutputField(
        desc = "The unique ID of the person, this is generated by the system and is always unique",
    )
    name: str = dspy.OutputField(
        desc = "The name of the person who is ingested, this is used to identify the person in the system",
    )
    action: str = dspy.OutputField(
        desc="The action that the user wants to take"
    )
    payload: dict = dspy.OutputField(
        desc="Other details of the person, this is used to store additional information about the person"
    )

class GenerateIntent(dspy.Signature):
    """
    To generate the intent of the person based on the details found.
    """
    user_id: int = dspy.InputField(
        desc = "The unique ID of the person, this is generated by the system and is always unique",
    )
    name: str = dspy.InputField(
        desc = "The name of the person who is ingested, this is used to identify the person in the system",
    )
    action: str = dspy.InputField(
        desc="The action that the user wants to take"
    )
    payload: dict = dspy.InputField(
        desc="Other details of the person, this is used to store additional information about the person"
    )
    intent: Literal['qualify', 'book', 'cancel', 'reject'] = dspy.OutputField() 





